### ISSUE TITLE
人脸对齐

### ISSUE THREAD

**Issue by zhouzhubin** [WindZu/facenet_facerecognition#2]
@WindZu 你好，请问你这里面用了人脸对齐吗？

**Comment by WindZu** [comment]
用了mtcnn

**Comment by windzu** [comment]
@zhouzhubin 用了mtcnn

**Comment by zhouzhubin** [comment]
@WindZu mtcnn有人脸对齐吗？怎么感觉扣出来的图没有对齐啊，在网上搜了说有用仿射变换或者相似性变换。

**Comment by xusk** [comment]
同一人的图片，距离0.48左右，区分度不大的问题？有什么好的解决办法？
