### ISSUE TITLE
这个东西要是放在树莓派上能不能带起来啊。。。

### ISSUE THREAD

**Issue by fawoo** [WindZu/facenet_facerecognition#5]
运行的时候资源开销怎么样呀。。。

**Comment by chijiao** [comment]
树莓派不行，我用r720，xen e5 40核cpu， 192g内存的服务器，跑这个程序， fps 大概只有10 左右，树莓派估计只有 0.01 fps吧， 根本没办法用

**Comment by tstin30** [comment]
加载模型太慢了
