### ISSUE TITLE
测试时，运行到model = joblib.load('./models/knn_classifier.model')异常

### ISSUE THREAD

**Issue by Monologuethl** [WindZu/facenet_facerecognition#7]
`Creating networks and loading parameters
Model directory: ./20170512-110547
Metagraph file: model-20170512-110547.meta
Checkpoint file: model-20170512-110547.ckpt-250000
WARNING:tensorflow:The saved meta_graph is possibly from an older release:
'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'.
WARNING:tensorflow:From C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\queue_runner_impl.py:391: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
```
建立facenet embedding模型

Process finished with exit code -1073741819 (0xC0000005)

```

**Comment by 2017011959ShenMeng** [comment]
> `Creating networks and loading parameters Model directory: ./20170512-110547 Metagraph file: model-20170512-110547.meta Checkpoint file: model-20170512-110547.ckpt-250000 WARNING:tensorflow:The saved meta_graph is possibly from an older release: 'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'. WARNING:tensorflow:From C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\queue_runner_impl.py:391: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version. Instructions for updating: To construct input pipelines, use the `tf.data` module.
> 
> ```
> 建立facenet embedding模型
> 
> Process finished with exit code -1073741819 (0xC0000005)
> ```

请问解决了吗？我也是报错这个问题，试了很多方法也不行。

**Comment by oooh-name** [comment]
> > `Creating networks and loading parameters Model directory: ./20170512-110547 Metagraph file: model-20170512-110547.meta Checkpoint file: model-20170512-110547.ckpt-250000 WARNING:tensorflow:The saved meta_graph is possibly from an older release: 'model_variables' collection should be of type 'byte_list', but instead is of type 'node_list'. WARNING:tensorflow:From C:\Users\Tong\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\queue_runner_impl.py:391: QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version. Instructions for updating: To construct input pipelines, use the `tf.data` module.
> > ```
> > 建立facenet embedding模型
> > 
> > Process finished with exit code -1073741819 (0xC0000005)
> > ```
> 
> 请问解决了吗？我也是报错这个问题，试了很多方法也不行。

我也是执行这一句代码时出的错,但是我这边报的是 segmentation fault (core dumped) ,然后我把scikit-learn换成0.19.1版本,能跑起来了
